:bug: Fix compatibility issue with Node.js v18 in ERD tool
This commit addresses a compatibility issue with Node.js v18 that causes the following error when running the command:

```
$ npx @liam-hq/cli erd build --input path/to/schema.rb --format schemarb
```

```
Error: Failed to parse schemarb file: wasi.getImportObject is not a function
```